Repository Gagechaeum/frontend, pull requests merged in 2025-09, with the labels that each got.

#22 라우터 추가, 수정 & 헤더 수정
  src/components/common/AppHeader.vue
  src/router/index.js
  src/views/Mypage/MyPageView.vue
Labels: 🐞Bug Fix

#23 [Feature] #18 : 커뮤니티 UI
  src/components/community/AllRoomsSection.vue
  src/components/community/ChatComposer.vue
  src/components/community/ChatMessages.vue
  src/components/community/ChatSidebar.vue
  src/components/community/ChatWindow.vue
  src/components/community/ImagePreviewModal.vue
  src/components/community/JoinModal.vue
  src/components/community/LiveBanner.vue
  src/components/community/MyRoomsSection.vue
  src/components/community/RecommendCarousel.vue
  src/router/index.js
  src/views/Community/CommunityView.vue
Labels: ✨New Feature

#26 [Feature] #16 : 마이페이지 UI
  src/components/mypage/BusinessItem.vue
  src/components/mypage/BusinessList.vue
  src/components/mypage/DeleteConfirmModal.vue
  src/components/mypage/EditProfileForm.vue
  src/components/mypage/ProfileDisplay.vue
  src/views/Mypage/MyPageView.vue
Labels: ✨New Feature

#25 [Feature] #24 : 리포트 UI
  package-lock.json
  package.json
  src/components/report/BottomPopover.vue
  src/components/report/CashflowChart.vue
  src/components/report/MonthlySummary.vue
  src/components/report/RegisterModal.vue
  src/components/report/ReportHeader.vue
  src/components/report/ReportList.vue
  src/components/report/TwoWeekCalendar.vue
  src/router/index.js
  src/views/Community/CommunityView.vue
  src/views/Report/ReportView.vue
Labels: ✨New Feature

#31 [Fix] #30 : 마이페이지 에러 수정
  src/views/Community/CommunityView.vue
Labels: 🐞Bug Fix

#33 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐞Bug Fix

#34 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐞Bug Fix

#39 [Feat] #38 : 마이페이지(header) 드롭다운 UI
  src/components/common/AppHeader.vue
  src/components/mypage/ProfileDropdown.vue
Labels: ✨New Feature

#47 [Feature] #43 : 일정 페이지 api 연동
  src/lib/api/bookmarks.js
  src/lib/api/schedule.js
  src/lib/api/search.js
  src/stores/favorites.js
  src/stores/scheduleData.js
  src/views/Schedule/AllSchedule.vue
  src/views/Schedule/FavoritesSchedule.vue
  src/views/Schedule/ListSchedule.vue
Labels: ✨New Feature

#51 [Feature] #42 : HomeView api 연동
  src/components/common/AppHeader.vue
  src/components/common/SearchResults.vue
  src/components/docs/ChecklistModal.vue
  src/components/docs/DocsHelperPanel.vue
  src/lib/api/attachAuthInterceptors.js
  src/lib/api/auth.js
  src/lib/api/community.js
  src/lib/api/documents.js
  src/lib/api/http.js
  src/lib/api/products.js
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/stores/docs.js
  src/stores/notification.js
  src/views/Detail/LoanDetailView.vue
  src/views/Detail/PolicyDetailView.vue
  src/views/Home/HomeView.vue
  src/views/docs/DocsView.vue
Labels: ✨New Feature, 🛠Refactor
